---
abstract: "MultiMarkdown 'filter' for Text::Xslate"
author:
  - 'William Wolf <throughnothing@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Xslate-Bridge-MultiMarkdown
requires:
  Text::MultiMarkdown: 0
  Text::Xslate::Bridge: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com//Text-Xslate-Bridge-MultiMarkdown.git
version: 0.002
